### Tarefa 1
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "title": "Faire la peau à Freezer",
  "priority": "high"
}

### Tarefa 2
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "title": "Boire un shot avec Vegeta",
  "priority": "medium",
  "completed": true
}

### Tarefa 3
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "title": "S'entraîner avec Maître Kaio",
  "priority": "high"
}

### Tarefa 4
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "title": "Aller chercher les Dragon Balls avec Bulma",
  "priority": "medium"
}

### Tarefa 5
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "title": "Manger 12 bols de ramen après l'entraînement",
  "priority": "low"
}

### Récupérer uniquement les tâches complétées
GET http://localhost:3000/api/tasks/completed

### Mettre à jour la première tâche (Goku a vaincu Freezer!)
PUT http://localhost:3000/api/tasks/COLA_O_ID_AQUI
Content-Type: application/json

{
  "completed": true
}